name: Config Direct Save
core: 8.x
description: This module allow you to export configuration after changes
type: module
package: Deployment

# Information added by Drupal.org packaging script on 2020-03-20
version: '8.x-1.1'
project: 'config_direct_save'
datestamp: 1584694480
